version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "aircraft-track-fusion"
resolve_s3 = false
s3_prefix = "aircraft-track-fusion"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=dev"
image_repositories = []
